spring.application.name=banquito-tariff-service
server.port=${SERVER_PORT:8086}
grpc.server.port=${GRPC_SERVER_PORT:9090}

spring.datasource.url=${POSTGRES_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
logging.level.ec.edu.espe.banquito.switchpayments.banquitotariffservice=DEBUG
